# Generated by Django 3.2.19 on 2023-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
